rules:
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order: concentric
      ignore-custom-properties: true
