files:
  include: '**/*.scss'
rules:
  no-ids: 2
  no-important: 2
  force-element-nesting: 0
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  indentation:
    - 1
    -
      size: 2
  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
